In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("nba_player_stats_C_Rami.csv")
df

,Player,Team,Points,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,Trp-Dbl,Season
0,Luka Dončić,DAL,2370.0,PG,70.0,70.0,2624.0,804.0,1652.0,0.487,...,59.0,588.0,647.0,686.0,99.0,38.0,282.0,149.0,21.0,2024
1,Shai Gilgeous-Alexander,OKC,2254.0,PG,75.0,75.0,2553.0,796.0,1487.0,0.535,...,65.0,350.0,415.0,465.0,150.0,67.0,162.0,184.0,0.0,2024
2,Giannis Antetokounmpo,MIL,2222.0,PF,73.0,73.0,2567.0,837.0,1369.0,0.611,...,196.0,645.0,841.0,476.0,87.0,79.0,250.0,210.0,10.0,2024
3,Jalen Brunson,NYK,2212.0,PG,77.0,77.0,2726.0,790.0,1648.0,0.479,...,43.0,235.0,278.0,519.0,70.0,13.0,186.0,144.0,0.0,2024
4,Nikola Jokić,DEN,2085.0,C,79.0,79.0,2737.0,822.0,1411.0,0.583,...,223.0,753.0,976.0,708.0,108.0,68.0,237.0,194.0,25.0,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17808,Yinka Dare,NJN,0.0,C,1.0,0.0,3.0,0.0,1.0,0.000,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,1995
17809,Tom Hovasse,ATL,0.0,SF,2.0,0.0,4.0,0.0,1.0,0.000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1995
17810,Rich King,SEA,0.0,C,2.0,0.0,6.0,0.0,2.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1995
17811,Derrick Phelps,SAC,0.0,PG,3.0,0.0,5.0,0.0,1.0,0.000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,1995
17812,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995

In [5]:
df_cleaned = df[df["Team"] != "2TM"]

df_cleaned.to_csv("nba_player_stats_cleaned.csv", index=False)